config/routes.rb
Rails.application.routes.draw do
  resources :file_operations

  root "contacts#index"
  resources :contacts do
  	collection do
  		get :import
  		post :import
      get :remove_dub
  	end
  end

  devise_for :users
  resources :users

  authenticate :user do
		mount Resque::Server, :at => '/resque'
	end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validate :user_id, presense: true

	def self.import(file, user_id)
		CSV.foreach(file, headers: true) do |row|
			Contact.create!(name: row['name'], number: row['number'], user_id: user_id)
		end
	end

	def self.remove_dublicated_contacts(user_id)
		hash = []
		counter = 1

		dublicated_by_number = self.where(user_id: user_id)
		dublicated_by_number.each do |obj|
			counter+=1

			if hash.map(&:number).include? obj.number
		    obj.destroy!
		  elsif hash.map(&:name).include? obj.name
		  	obj.update_attribute(:name, "#{obj.name}_#{counter}")
		  	hash << obj
		  else
		    hash << obj
		  end
		end
	end
end

app/models/file_operation.rb
class FileOperation < ActiveRecord::Base
	belongs_to :user

	validates :user_id, presence: true
	validates :file_path, presence: true

  def self.create_and_enqueue(klass, user, *params)
    if klass == ContactsImportJob
  	  create_file(params.first[:file]) 
      export_file = FileOperation.create!(:job_class => klass.to_s, :user => user, file_path: import_path(params.first[:file]))
    else
      export_file = FileOperation.create!(:job_class => klass.to_s, :user => user, file_path: export_path)
    end

    Resque.enqueue(klass, export_file.id, user.id, *params)
  end

  def self.import_path(options)
    File.join(Rails.root, "/files/import/#{Time.now.to_s(:db)[0..9]}/#{options.original_filename}")
  end

  def self.create_file(options)
    FileUtils.mkdir_p(File.dirname(import_path(options))) unless File.exists?(File.dirname(import_path(options)))
    FileUtils.cp(options.tempfile.to_path, import_path(options))
  end

  def self.export_path
    path = File.join(Rails.root, "/files/export/#{Time.now.to_s(:db)[0..9]}/contacts.csv")
    FileUtils.mkdir_p(File.dirname(path)) unless File.exists?(File.dirname(path))
    csv_file = File.new(path, "w")
    csv_file.close
    path
  end

  def file_type
    self.file_name.last(3)
  end

  private

  # def set_file_name
  #   self.file_name = "#{self.created_at.to_s(:db).parameterize}.csv"
  #   self.save!
  # end

  # def delete_csv_file
  #   FileUtils.rm_r(File.dirname(path)) if File.exists?(path)
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
  has_many :file_operations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:edit, :update, :destroy]

  def index
    @contacts = Contact.where(user_id: current_user.id)
    respond_to do |format|
      format.html
      format.csv do
        FileOperation.create_and_enqueue(ContactsExportJob, current_user, {ids: @contacts.pluck(:id)})
        redirect_to file_operations_url, notice: "Contacts export is schedule!"
      end
    end
  end

  def import
    if params[:file]
      FileOperation.create_and_enqueue(ContactsImportJob, current_user, params)
      redirect_to root_url, notice: "Contacts imported is schedule!"
    end
  end

  def remove_dub
    Resque.enqueue(RemoveDublicationJob, current_user.id)
    redirect_to root_url, notice: "Removing dublications is schedule!"
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :number)
    end
end

app/controllers/file_operations_controller.rb
class FileOperationsController < ApplicationController
  before_action :set_file_operation, only: [:show, :destroy]

  def index
    @file_operations = FileOperation.where(user_id: current_user.id, job_class: 'ContactsExportJob')
  end

  def show
    @file = FileOperation.find(params[:id])
    file_name = @file.file_path.split('/').last
    logger.debug("~" * 80)
    logger.debug(@file.file_path)
    logger.debug(file_name)
    logger.debug("~" * 80)

    send_file(@file.file_path, :filename => file_name)
  end

  def destroy
    @file_operation.destroy
    respond_to do |format|
      format.html { redirect_to file_operations_url, notice: 'File operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_operation
      @file_operation = FileOperation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_operation_params
      params.require(:file_operation).permit(:file_path, :status, :job_class, :user_type, :user_id, :info)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/file_operations_helper.rb
module FileOperationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :number
    = f.text_field :number
  .actions
    = f.submit 'Save'

app/views/contacts/edit.html.haml
%h3 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/import.html.haml
%h3 Import Contacts

= form_tag import_contacts_path, multipart: true do
  = file_field_tag :file
  = submit_tag 'Import'

app/views/contacts/index.html.haml
%h3 Contacts

%table.table-striped
  %tr
    %th Name
    %th Number
    %th
    %th

  - @contacts.each do |contact|
    %tr
      %td= contact.name
      %td= contact.number
      %td= link_to 'Edit', edit_contact_path(contact)
      %td= link_to 'Destroy', contact, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Export CSV', contacts_path(format: 'csv')
%br

= link_to 'Remove dublications', remove_dub_contacts_path

app/views/contacts/new.html.haml
%h3 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/file_operations/_form.html.haml
= form_for @file_operation do |f|
  - if @file_operation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@file_operation.errors.count, "error")} prohibited this file_operation from being saved:"
      %ul
        - @file_operation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :file_path
    = f.text_field :file_path
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :job_class
    = f.text_field :job_class
  .field
    = f.label :user_type
    = f.text_field :user_type
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :info
    = f.text_area :info
  .actions
    = f.submit 'Save'

app/views/file_operations/index.html.haml
%h3 Exported Files

%table
  %tr
    %th File name
    %th Status
    %th
    %th

  - @file_operations.each do |file_operation|
    %tr
      %td= file_operation.file_path.split('/').last
      %td= file_operation.status
      %td= link_to 'Download', file_operation
      %td= link_to 'Destroy', file_operation, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/layouts/_footer.html.haml
%footer.footer
	= "Designed by: Hristo Tanchev & Genislav Hristov"

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{role: 'navigation'}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle' => 'collapse', type: 'button'}
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav#MainNavigation
        %li
          %a{href: root_path} Home
        - if signed_in?
          %li
            %a{:href => import_contacts_path} Import Contacts
          %li
            %a{:href => new_contact_path} New Contact
          %li
            %a{:href => file_operations_path} Export Files
        %li.dropdown
          %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
            = User
            %span.caret
          %ul.dropdown-menu{role: 'menu'}
            - if signed_in?
              %li
                %a{href: edit_user_registration_path} Profile
              %li.divider
              %li
                = link_to 'Log Out', destroy_user_session_path, :method => :delete
            - else
              %li
                %a{href: new_user_session_path} Log In
              %li
                %a{href: new_user_registration_path} Sign Up

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %title
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true                  |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    .container
      = render 'layouts/header'
    .container
      .jumbotron
        .row
          .span12
            - flash.each do |key, value|
              - if key == 'notice'
                - @flash_class = 'success'
              - else
                - @flash_class = 'danger'

              %div{class: "alert alert-#{@flash_class}"}
                %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} ×
                = content_tag(:h3, value, class: "alert alert-#{key}", class: 'text-center')
            = yield
    .container
      .row
        .col-md-4
        .col-md-4
          = render 'layouts/footer'

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path